workflows:
  android-workflow:
    name: MORAD TK Android Local-Core Workflow
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK Release
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
